parameters:
  datalake:
    basePath: '/%kernel.environment%'

  datalakebundle:
    tables:
      # bronze ------------------------------------------
      bronze_covid.tbl_template_1_mask_usage:
        params:
          source_csv_path: 'dbfs:/databricks-datasets/COVID/covid-19-data/mask-use/mask-use-by-county.csv'

      bronze_covid.tbl_template_2_confirmed_cases:
        params:
          source_csv_path: 'dbfs:/databricks-datasets/COVID/USAFacts/covid_confirmed_usafacts.csv'

      # silver ------------------------------------------
      silver_covid.tbl_template_3_mask_usage:

      # gold --------------------------------------------
      gold_reporting.tbl_template_4_mask_usage_per_county:

      gold_solutions.template_5_solution:

  featurestorebundle:
    entities:
      - name: 'customer'
        historization: True
