[tool.poetry]
name = "t__myproject__t"
version = "0.1"
description = "Bricksflow project skelefon"
readme = "README.md"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml", "*.json"]

packages = [
    { include = "__myproject__", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
pyfony = "0.6.*"
databricks-bundle = "0.5.10"

[tool.poetry.dev-dependencies]
databricks-connect = "7.1.*"
dbx-deploy = "^0.12.1"
pylint = "2.4.*"
py4j = "^0.10.9"
deepdiff = "^4.3.2"

[app]
container-init = ["__myproject__.ContainerInit", "initContainer"]
